version: "3"  # optional since v1.27.0
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - TZ=US/Eastern
      - JELLYFIN_PublishedServerUrl=10.38.85.12 #optional
    volumes:
      - /media/daiyousei:/media/daiyousei
      - /media/daiyousei/jellyfin:/config
    ports:
      - 8096:8096
    restart: unless-stopped

  flood:
    container_name: flood
    hostname: flood
    image: jesec/flood
    user: "${UID}:${GID}"
    restart: unless-stopped
    command: --port 3001
    depends_on:
      - rtorrent
    environment:
      HOME: /config
    volumes:
      - /home/cirno/dlconfig:/config
      - /media/daiyousei:/data
    ports:
      - 0.0.0.0:3001:3001

  rtorrent:
    container_name: rtorrent
    hostname: rtorrent
    image: jesec/rtorrent
    user: "${UID}:${GID}"
    restart: unless-stopped
    command: -o network.port_range.set=6881-6881,system.daemon.set=true
    environment:
      HOME: /config
    volumes:
      - /home/cirno/dlconfig:/config
      - /media/daiyousei:/data
    ports:
      - 0.0.0.0:6881:6881

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - 0.0.0.0:9100:9100

  telegraf:
    container_name: telegraf
    image: telegraf
    hostname: cirno
    restart: unless-stopped
    ports:
      - 0.0.0.0:9273:9273
    volumes:
      - $PWD/../../configs/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/dopcker.sock
      - /:/hostfs:ro
    environment:
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs

